// <auto-generated />
using System;
using ClaimWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClaimWebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221226055512_initialSetup")]
    partial class initialSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClaimWebApp.Models.ClaimRequest", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimId"));

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ExpenseTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsOtherExpense")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MileageTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OtherExpenseTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ClaimId");

                    b.ToTable("ClaimRequests");
                });

            modelBuilder.Entity("ClaimWebApp.Models.ExpenseClaim", b =>
                {
                    b.Property<int>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenseId"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ClaimRequestClaimId")
                        .HasColumnType("int");

                    b.Property<string>("ExpenseDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExpenseId");

                    b.HasIndex("ClaimRequestClaimId");

                    b.ToTable("ExpenseClaims");
                });

            modelBuilder.Entity("ClaimWebApp.Models.MileageClaim", b =>
                {
                    b.Property<int>("MileageClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MileageClaimId"));

                    b.Property<int?>("ClaimRequestClaimId")
                        .HasColumnType("int");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Distance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FromWhere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TripDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MileageClaimId");

                    b.HasIndex("ClaimRequestClaimId");

                    b.ToTable("MileageClaims");
                });

            modelBuilder.Entity("ClaimWebApp.Models.OtherExpenseClaim", b =>
                {
                    b.Property<int>("OtherExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OtherExpenseId"));

                    b.Property<int?>("ClaimRequestClaimId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OtherExpenseId");

                    b.HasIndex("ClaimRequestClaimId");

                    b.ToTable("OtherExpenseClaims");
                });

            modelBuilder.Entity("ClaimWebApp.Models.ExpenseClaim", b =>
                {
                    b.HasOne("ClaimWebApp.Models.ClaimRequest", null)
                        .WithMany("ExpenseClaims")
                        .HasForeignKey("ClaimRequestClaimId");
                });

            modelBuilder.Entity("ClaimWebApp.Models.MileageClaim", b =>
                {
                    b.HasOne("ClaimWebApp.Models.ClaimRequest", null)
                        .WithMany("MileageClaims")
                        .HasForeignKey("ClaimRequestClaimId");
                });

            modelBuilder.Entity("ClaimWebApp.Models.OtherExpenseClaim", b =>
                {
                    b.HasOne("ClaimWebApp.Models.ClaimRequest", null)
                        .WithMany("OtherExpenseClaims")
                        .HasForeignKey("ClaimRequestClaimId");
                });

            modelBuilder.Entity("ClaimWebApp.Models.ClaimRequest", b =>
                {
                    b.Navigation("ExpenseClaims");

                    b.Navigation("MileageClaims");

                    b.Navigation("OtherExpenseClaims");
                });
#pragma warning restore 612, 618
        }
    }
}
